AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  LFA:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: yz3831_hw3_2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_function.py
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::574370168117:role/service-role/yz3831_hw3_2-role-07280xi3'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get
      Environment:
        Variables:
          REGION: us-east-1
