AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  LFA:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: yz3831_hw3_2_demo
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_function.py
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::574370168117:role/service-role/yz3831_hw3_2-role-07280xi3'
      Environment:
        Variables:
          REGION: us-east-1
  LFB:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index_photos_demo
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./index_photos/lambda_function.py
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::574370168117:role/service-role/index_photos-role-eve2mwmt'
      Environment:
        Variables:
          REGION: us-east-1
